version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: cesizen
      POSTGRES_USER: cesi
      POSTGRES_PASSWORD: cesi
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    depends_on: [db]
    environment:
      DATABASE_URL: postgres://cesi:cesi@db:5432/cesizen
      DJANGO_SETTINGS_MODULE: cesizen_backend.settings
      PYTHONUNBUFFERED: "1"
    ports: ["8000:8000"]
    volumes:
      - .:/app
volumes:
  pgdata:
