version: "3.9"
services:
  db:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cesizen}
      POSTGRES_USER: ${POSTGRES_USER:-cesizen}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER:-cesizen} -d ${POSTGRES_DB:-cesizen}"]
      interval: 10s
      timeout: 5s
      retries: 6
    restart: unless-stopped

  web:
    build:
      context: ./cesizen_backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-cesizen}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-cesizen}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./cesizen_backend:/app

volumes:
  pgdata:
