name: Release Image
on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push versioned image
        run: |
          VER=${GITHUB_REF##*/}
          IMAGE=ghcr.io/${{ github.repository }}:$VER
          docker build -t $IMAGE .
          docker push $IMAGE