name: Release Image
on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Extract version + repo (lowercase)
        id: meta
        run: |
            VER="${GITHUB_REF##*/}"
            echo "ver=$VER" >> $GITHUB_OUTPUT
            BASE="${VER#v}"
            MAJOR="${BASE%%.*}"
            MINOR="${BASE%.*}"
            echo "tag_major=v${MAJOR}" >> $GITHUB_OUTPUT
            echo "tag_minor=v${MINOR}" >> $GITHUB_OUTPUT
            REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
            echo "repo=$REPO_LC" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.ver }}
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag_minor }}
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag_major }}
            ghcr.io/${{ steps.meta.outputs.repo }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max