name: Release Image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        run: |
          VERSION=${GITHUB_REF##*/}
          IMAGE=ghcr.io/${{ github.repository }}:${VERSION}
          docker build -t $IMAGE .
          docker push $IMAGE